Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -26,12 +26,33 @@ jobs:
         run: |
           echo "old_tag_name=$(git ls-remote --tags origin | awk -F'/' '{print $3}' | grep -v '{}' | sort -V | tail -n1)" >> $GITHUB_ENV
   
+      - name: print tag
+        id: print_tag
+        run: | 
+          echo "Old Tag: ${{ steps.get_tag.outputs.old_tag_name }}"
+          echo "LATEST_TAG=${{ steps.get_tag.outputs.old_tag_name }}" >> $GITHUB_ENV
+          echo "NEW_TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
+              
+      - name: Check if new tag already exists
+        id: check_tag
+        run: |
+          if git rev-parse ${{ env.NEW_TAG }} >/dev/null 2>&1; then
+            echo "Error: Tag '${{ env.NEW_TAG }}' already exists."
+            exit 1
+          fi
+        continue-on-error: false
+        shell: bash
+      - name: Handle Failure
+        if: failure()
+        run: |
+          echo "Tag already exists. Workflow failed."
+
   update-params-env:
     runs-on: ubuntu-latest
     needs: fetch-tag
     outputs:
       param_env: ${{ steps.read_params_env.outputs.params_env }}
-      release_version: ${{ steps.get_release_version.outputs.release_version }}
+      # release_version: ${{ steps.get_release_version.outputs.release_version }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -41,9 +62,9 @@ jobs:
         run: |
           echo "params_env=$(cat config/params.env)" >> $GITHUB_ENV
               
-      - name: Read release version
-        id: get_release_version
-        run: echo "release_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
+      # - name: Read release version
+      #   id: get_release_version
+      #   run: echo "release_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
               
       - name: Update params.env with new release version
         run: |     
@@ -58,7 +79,7 @@ jobs:
 
   changelog:
     name: Build Changelog
-    needs: [fetch-tag]
+    needs: update-params-env
     runs-on: ubuntu-latest
     outputs:
       changelog: ${{ steps.build_changelog.outputs.changelog }}
@@ -90,7 +111,7 @@ jobs:
     
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
       - name: Generate Release Notes
         run: echo ${{ env.changelog }}
       - name: Create Release
