Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,16 +28,13 @@ jobs:
       - name: Compare tags
         id: compare_tags
         run: |
-          old_tag= ${{ steps.get_tag.outputs.old_tag_name }}
-          new_tag= ${{ github.event.inputs.tag_name }}
-          if [[ "$new_tag" == "$latest_tag" ]]; then
-            echo "Error: Tag '$new_tag' already exists."
-            exit 1
-          elif [[ "$new_tag" > "$latest_tag" ]]; then
-            echo "Error: The New tag '$new_tag' already exists '$latest_tag'."
+          latest_tag=${{ steps.get_tag.outputs.latest_tag }}
+          new_tag=${{ github.event.inputs.tag_name }}
+          if ! dpkg --compare-versions "$new_tag" gt "$latest_tag"; then
+            echo "Error: New tag '$new_tag' is not greater than the latest tag '$latest_tag'."
             exit 1
           fi
-          echo "New tag created '$new_tag' is valid '$latest_tag'."
+          echo "New tag '$new_tag' is valid and greater than the latest tag '$latest_tag'."
    changelog:
       name: Build Changelog
       needs: [fetch-tag]
