Update superrelease.yml

diff --git a/.github/workflows/superrelease.yml b/.github/workflows/superrelease.yml
--- a/.github/workflows/superrelease.yml
+++ b/.github/workflows/superrelease.yml
@@ -67,7 +67,8 @@ jobs:
         run: |
           if git rev-parse "${{ github.event.inputs.tag_name }}" >/dev/null 2>&1; then
             echo "Error: Tag '${{ github.event.inputs.tag_name }}' already exists."
-            fail "Tag already exists" 
+            echo "::error::Tag '${{ github.event.inputs.tag_name }}' already exists."
+            exit 1
           fi
         continue-on-error: false
         shell: bash
