Update superrelease.yml

diff --git a/.github/workflows/superrelease.yml b/.github/workflows/superrelease.yml
--- a/.github/workflows/superrelease.yml
+++ b/.github/workflows/superrelease.yml
@@ -27,29 +27,13 @@ jobs:
         id: get_tag
         run: |
           echo "old_tag_name=$(git ls-remote --tags origin | awk -F'/' '{print $3}' | grep -v '{}' | sort -V | tail -n1)" >> $GITHUB_OUTPUT
-  
       - name: print tag
         id: print_tag
         run: | 
           echo "Old Tag=${{ steps.get_tag.outputs.old_tag_name }}"
           echo "NEW_TAG=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
           echo "$(basename ${{ github.ref }})"
-      
-      - name: Check if new tag already exists
-        id: check_tag
-        run: |
-          if git rev-parse ${{ env.NEW_TAG }} >/dev/null 2>&1; then
-            echo "Error: Tag '${{ env.NEW_TAG }}' already exists."
-            exit 1
-          fi
-        continue-on-error: false
-        shell: bash
-      - name: Handle Failure
-        if: failure()
-        run: |
-          exit 1
-          echo "Tag already exists. Workflow failed."
-
+  
   update-params-env:
     runs-on: ubuntu-latest
     needs: fetch-tag
@@ -77,8 +61,19 @@ jobs:
           git add config/params.env
           git commit -m "Update image refs for odh release."
           git push 
+
+      - name: Check if tag exists
+        id: check_tag
+        run: |
+          if git rev-parse "${{ github.event.inputs.tag_name }}" >/dev/null 2>&1; then
+            echo "Error: Tag '${{ github.event.inputs.tag_name }}' already exists."
+            exit 1
+          fi
+        continue-on-error: false
+        shell: bash
       - name: Create Tag
         id: create_tag
+        if: steps.check_tag.outcome == 'success'
         run: |
           git tag -a ${{ github.event.inputs.tag_name }} -m "Prepare for ODH release ${{ github.event.inputs.tag_name }}"
           git push origin ${{ github.event.inputs.tag_name }}
@@ -96,13 +91,6 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.ref }}
-      # - name: Generate Changelog
-      #   id: generate_changelog
-      #   uses: mikepenz/release-changelog-builder-action@v4
-      #   with:
-      #     fromTag: ${{ needs.fetch-tag.outputs.old_tag }}
-      #     toTag:  ${{ github.event.inputs.tag_name }}
-      #     token: ${{ github.token }}
 
       - name: Create Release
         uses: softprops/action-gh-release@v2
@@ -114,7 +102,4 @@ jobs:
           files: bin/*
           generate_release_notes: true
           name: ${{ github.event.inputs.tag_name }}
-          # body: ${{ steps.generate_changelog.outputs.changelog }}
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
-
+       
